name: Build Calm Hub For Unit Test Coverage

permissions:
    contents: read

on:
    pull_request:
        branches:
            - 'main'
    push:
        branches:
            - 'main'

jobs:
    build:
        name: Build Calm Hub
        runs-on: ubuntu-latest

        steps:
            # Step 1: Checkout PR Branch
            - name: Checkout PR Branch
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

            # Step 2: Set up JDK
            - name: Set up JDK
              uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5
              with:
                  distribution: 'temurin'
                  java-version: '21'

            # Step 3: Cache Maven Dependencies
            - name: Cache Maven Dependencies
              uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
              with:
                  path: ~/.m2
                  key: ${{ runner.os }}-m2-${{ hashFiles('calm-hub/pom.xml') }}
                  restore-keys: |
                      ${{ runner.os }}-m2-

                        # Step 4: Build and Test
                        - name: Build and Test
                            working-directory: calm-hub
                            run: mvn clean verify -Ddependency-check.skip=true
